---
# unarchive tasks file for ghidra
- name: Create a temporary directory for unarchive
  tempfile:
    state: directory
  register: ghidra_temp_dir
  notify: Remove temporary Ghidra directory
  when: not ansible_check_mode

- name: Fail if archive src is not set
  fail:
    msg: To unarchive ghidra_archive_src must be set
  when: ghidra_archive_src | length == 0

- name: Unarchive the source archive
  unarchive:
    src: "{{ ghidra_archive_src }}"
    dest: "{{ ghidra_temp_dir.path }}"
    list_files: yes
    remote_src: "{{ '://' in ghidra_archive_src }}"
  register: ghidra_unarchived_content
  when: not ansible_check_mode

- name: List unarchived parent dirs
  set_fact:
    unarchived_parents: "{{ ghidra_unarchived_content.files | map('reverse') | map('basename') | map('reverse') | list | unique }}"
  when: not ansible_check_mode

- name: Fail if there is not exactly one parent
  fail:
    msg: Archive does not contain exactly one top level directory
  when:
    - not ansible_check_mode
    - unarchived_parents | length != 1
